[[language]]
name = "latex"

[language.config.texlab.build]
onSave = true
forwardSearchAfter = true
executable = "latexmk"
args = [
  "-pdf",
  "-interaction=nonstopmode",
  "-synctex=1",
  # "-c",
  "-lualatex",
 # "-shell-escape",
 # "-output-directory=build",
 "%f"
 ]

[language.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:1:%f", "%p" ]

[language.config.texlab.chktex]
onEdit = true