# Lines configured by zsh-newuser-install
HISTFILE=~/.local/share/zsh/.histfile
HISTSIZE=1000
SAVEHIST=100000
setopt autocd beep extendedglob nomatch notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/var/home/jakob/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Environment Variables
export EDITOR=nvim
export VISUAL=nvim

# Aliases
alias ls="ls -A --group-directories-first -h -l -1 --color=auto"
alias vi="$EDITOR"

# configuration options for nnn
export NNN_TRASH=1
alias nnn="nnn -R"

# Plugins
# source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Prompt
autoload -Uz vcs_info

zstyle ':vcs_info:*' actionformats '%F{white}[%F{2}%b%F{3}|%F{1}%a%F{white}]%f '
zstyle ':vcs_info:*' formats '%F{white}[%F{2}%b%F{white}]%f '
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{3}%r'

precmd() {
    vcs_info
}
setopt prompt_subst
PS1='%F{yellow}%3~ ${vcs_info_msg_0_}%f%# '

lfcd () {
    tmp="$(mktemp)"
    # `command` is needed in case `lfcd` is aliased to `lf`
    command lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}
alias lf="lfcd"
